# Generated by Django 5.1.2 on 2024-10-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        choices=[
                            ("AGO", "AGO"),
                            ("UX", "UX"),
                            ("LUBRICANTS", "LUBRICANTS"),
                        ],
                        default="AGO",
                        max_length=100,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle_number",
                    models.CharField(
                        help_text="Enter vehicle number (letter and numbers allowed)",
                        max_length=20,
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter driver's name (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "driver_id_number",
                    models.CharField(
                        blank=True,
                        help_text="Enter driver's ID number or Telephone (optional)",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
