# Generated by Django 5.1.2 on 2024-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_userprofile_status_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
