# Generated by Django 5.1.2 on 2024-10-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_userprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="approved_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("collected", "Collected"),
                    ("on hold", "On Hold"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
