# Generated by Django 5.1.2 on 2024-11-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_approved_status_order_account_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Load_Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Type", models.CharField(max_length=50)),
                ("Date", models.DateField()),
                ("Num", models.CharField(max_length=50)),
                ("Name", models.CharField(max_length=50)),
                ("Memo", models.CharField(max_length=50)),
                ("Item", models.CharField(max_length=50)),
                ("Qty", models.PositiveIntegerField(max_length=50)),
                ("Sales_Price", models.PositiveIntegerField(max_length=50)),
                ("Amount", models.PositiveIntegerField(max_length=50)),
                ("Balance", models.PositiveIntegerField(max_length=50)),
            ],
        ),
    ]
