# Generated by Django 5.1.2 on 2024-11-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_load_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load_sales",
            name="Amount",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="load_sales",
            name="Balance",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="load_sales",
            name="Qty",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="load_sales",
            name="Sales_Price",
            field=models.CharField(max_length=50),
        ),
    ]
