# Generated by Django 5.1.2 on 2024-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_load_sales_amount_alter_load_sales_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Type", models.CharField(blank=True, max_length=100, null=True)),
                ("Date", models.DateField()),
                ("Num", models.CharField(blank=True, max_length=50, null=True)),
                ("Name", models.CharField(blank=True, max_length=200, null=True)),
                ("Memo", models.CharField(blank=True, max_length=50, null=True)),
                ("Item", models.CharField(max_length=100)),
                ("Qty", models.IntegerField()),
                ("Sales_Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Balance", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Load_Sales",
        ),
    ]
